MACRO (FINDAVFORMAT _lib)

FIND_PATH(AVFORMAT_INCLUDE_DIR_FF "ffmpeg/avformat.h" PATHS)
IF (AVFORMAT_INCLUDE_DIR_FF)
      SET (AVFORMAT_INCLUDE_DIR "${AVCODEC_INCLUDE_DIR_FF}/ffmpeg")
ELSE (AVFORMAT_INCLUDE_DIR_FF)
      FIND_PATH(AVFORMAT_INCLUDE_DIR_LAVC "libavformat/avformat.h" PATHS)
      IF (AVFORMAT_INCLUDE_DIR_LAVC)
          SET (AVFORMAT_INCLUDE_DIR "${AVFORMAT_INCLUDE_DIR_LAVC}/libavformat")
      ELSE (AVFORMAT_INCLUDE_DIR_LAVC)
	  FIND_PATH(AVFORMAT_INCLUDE_DIR_FF_LAVF "ffmpeg/libavformat/avformat.h" PATHS)
	  IF (AVFORMAT_INCLUDE_DIR_FF_LAVF)
	    SET (AVFORMAT_INCLUDE_DIR "${AVFORMAT_INCLUDE_DIR_FF_LAVF}/ffmpeg/libavformat")
	  ENDIF (AVFORMAT_INCLUDE_DIR_FF_LAVF)
      ENDIF (AVFORMAT_INCLUDE_DIR_LAVC)
ENDIF (AVFORMAT_INCLUDE_DIR_FF)



FIND_LIBRARY(AVFORMAT_LIBRARY NAMES ${_lib} PATHS ) 

IF (AVFORMAT_INCLUDE_DIR AND AVFORMAT_LIBRARY)
   SET(INC_FOUND TRUE)
ELSE (AVFORMAT_INCLUDE_DIR AND AVFORMAT_LIBRARY)
      SET(INC_FOUND FALSE)
ENDIF (AVFORMAT_INCLUDE_DIR AND AVFORMAT_LIBRARY)


IF (INC_FOUND)
      MESSAGE(STATUS "Found include avformat.h: ${AVFORMAT_INCLUDE_DIR}")
      MESSAGE(STATUS "Found library ${_lib}: ${AVFORMAT_LIBRARY}")
ELSE (INC_FOUND)
      MESSAGE(FATAL_ERROR "Could not find ${_lib}")
ENDIF (INC_FOUND)
ENDMACRO (FINDAVFORMAT _lib )