MACRO (FINDFFMPEGSCALE  _lib)


FIND_PATH(FFMPEGSCALE_INCLUDE_DIR_FF "ffmpeg/swscale.h" PATHS)
IF (FFMPEGSCALE_INCLUDE_DIR_FF)
      SET (FFMPEGSCALE_INCLUDE_DIR "${FFMPEGSCALE_INCLUDE_DIR_FF}/ffmpeg")
ELSE (FFMPEGSCALE_INCLUDE_DIR_FF)
      FIND_PATH(FFMPEGSCALE_INCLUDE_DIR_LAVC "libswscale/swscale.h" PATHS)
      IF (FFMPEGSCALE_INCLUDE_DIR_LAVC)
          SET (FFMPEGSCALE_INCLUDE_DIR "${FFMPEGSCALE_INCLUDE_DIR_LAVC}/libswscale")
      ELSE (FFMPEGSCALE_INCLUDE_DIR_LAVC)
	  FIND_PATH(FFMPEGSCALE_INCLUDE_DIR_FF_SCAL "ffmpeg/libswscale/swscale.h" PATHS)
	  IF (FFMPEGSCALE_INCLUDE_DIR_FF_SCAL)
	    SET (FFMPEGSCALE_INCLUDE_DIR "${FFMPEGSCALE_INCLUDE_DIR_FF_SCAL}/ffmpeg/libswscale")
	  ENDIF (FFMPEGSCALE_INCLUDE_DIR_FF_SCAL)
      ENDIF (FFMPEGSCALE_INCLUDE_DIR_LAVC)
ENDIF (FFMPEGSCALE_INCLUDE_DIR_FF)



FIND_LIBRARY(FFMPEGSCALE_LIBRARY NAMES ${_lib} PATHS ) 

IF (FFMPEGSCALE_INCLUDE_DIR AND FFMPEGSCALE_LIBRARY)
   SET(HAVE_SWSCALE TRUE)
ELSE (FFMPEGSCALE_INCLUDE_DIR AND FFMPEGSCALE_LIBRARY)
   SET(HAVE_SWSCALE FALSE)
ENDIF (FFMPEGSCALE_INCLUDE_DIR AND FFMPEGSCALE_LIBRARY)


IF (HAVE_SWSCALE)
      MESSAGE(STATUS "Found library ${_lib}: ${FFMPEGSCALE_LIBRARY}")
      MESSAGE(STATUS "Found include swscale.h : ${FFMPEGSCALE_INCLUDE_DIR}")
ELSE (HAVE_SWSCALE)
      MESSAGE(STATUS "k9copy will be built without swscale support")
      #MESSAGE(FATAL_ERROR "Could not find ${_lib}")
ENDIF (HAVE_SWSCALE)
ENDMACRO (FINDFFMPEGSCALE _lib )