MACRO (FINDLIBMPEG2 _include _lib)

FIND_PATH(LIBMPEG2_INCLUDE_DIR ${_include} PATHS)
FIND_LIBRARY(LIBMPEG2_LIBRARY NAMES ${_lib} PATHS ) 

IF (LIBMPEG2_INCLUDE_DIR AND LIBMPEG2_LIBRARY)
   SET(INC_FOUND TRUE)
ELSE (LIBMPEG2_INCLUDE_DIR AND LIBMPEG2_LIBRARY)
   SET(INC_FOUND FALSE)
ENDIF (LIBMPEG2_INCLUDE_DIR AND LIBMPEG2_LIBRARY)


IF (INC_FOUND)
      MESSAGE(STATUS "Found library ${_lib}: ${LIBMPEG2_LIBRARY}")
      MESSAGE(STATUS "Found include ${_include} : ${LIBMPEG2_INCLUDE_DIR}")
ELSE (INC_FOUND)
      MESSAGE(FATAL_ERROR "Could not find ${_lib}")
ENDIF (INC_FOUND)
ENDMACRO (FINDLIBMPEG2 _include _lib )