MACRO (FINDLIBDVDREAD _include _lib)

FIND_PATH(LIBDVDREAD_INCLUDE_DIR ${_include} PATHS)
FIND_LIBRARY(LIBDVDREAD_LIBRARY NAMES ${_lib} PATHS )

IF (LIBDVDREAD_INCLUDE_DIR AND LIBDVDREAD_LIBRARY)
   SET(INC_FOUND TRUE)
ELSE (LIBDVDREAD_INCLUDE_DIR AND LIBDVDREAD_LIBRARY)
   SET(INC_FOUND FALSE)
ENDIF (LIBDVDREAD_INCLUDE_DIR AND LIBDVDREAD_LIBRARY)


IF (INC_FOUND)
      MESSAGE(STATUS "Found library ${_lib}: ${LIBDVDREAD_LIBRARY}")
      MESSAGE(STATUS "Found include ${_include} : ${LIBDVDREAD_INCLUDE_DIR}")
ELSE (INC_FOUND)
      MESSAGE(FATAL_ERROR "Could not find ${_lib}")
ENDIF (INC_FOUND)
ENDMACRO (FINDLIBDVDREAD _include _lib )
